### ISSUE TITLE
a bug, a possible bug, and a noteworthy point

### ISSUE THREAD

**Issue by pkoppstein** [fadado/CSV#1]
@fadado - Running your csv2json program against test.csv reveals one bug,
one questionable behavior, and one noteworthy point.

The bug is that csv2json should produce JSON but the  line produced by line 20 has an embedded raw tab:

    ["20","embedded tab","	","d"] # invalid JSON

The questionable behavior is the production of invalid (incomplete) JSON at the line numbered 100:

["100","  # !! incomplete

Your decision NOT to ignore empty lines in general is noteworthy, if only because
some CSV parsers do, e.g. R (using `read.csv("empty.csv",
header=FALSE, fill=TRUE)`). 

Perhaps you'll agree that ideally the treatment of empty lines would be
governed by an option, as once they've been read as [""] there's no
way to distinguish an empty line from a row with one empty string;
and conversely, if it's ignored, there's no way to tell if it was there :-)

Incidentally, another command-line option worthy of consideration
would be the interpretation of null fields as JSON `null` values
instead of as empty JSON strings.

Thanks!

**Comment by fadado** [comment]
@pkoppstein 
> The bug is that csv2json should produce JSON but the line produced by line 20 has an embedded raw tab:

Yes, a true bug. Fixed. Thanks! 
Input tabs are now translated to `\t` inside strings.

> The questionable behavior is the production of invalid (incomplete) JSON at the line numbered 100:
> ["100"," # !! incomplete

Fixed. Now a "correct" but incomplete array is emited before aborting. In case of error the last record emited is complete but "wrong". This generates correct and complete JSON to stdout:

```
$ ./csv2json < test.csv | jq -c .
```

About your comments on empty input lines I decided to emit `null`, not an array. Do you thing it is a god idea?

And finally, I will work to  make "the interpretation of null fields as JSON null values", but this must wait.

**Comment by pkoppstein** [comment]
Thanks for attending to the bug, the “bug”, and the update regarding the handling of empty lines.  Emitting `null`  is easily justifiable, and I believe by far the best of all possible uniform-behavior alternatives, as it gives the user complete control.

Except possibly for encoding-related issues, your csv2json is to my knowledge  now unsurpassed in terms of its combination of robustness and efficiency, and I hope it makes its way into jq soon.

**Comment by fadado** [comment]
> I will work to make "the interpretation of null fields as JSON null values"

Done! I also implemented all design options as compile time flags.  

<https://github.com/fadado/CSV/blob/master/csv2json.h>
<https://github.com/fadado/CSV/blob/master/csv2json.c>
