### ISSUE TITLE
CR / LF

### ISSUE THREAD

**Issue by pkoppstein** [fadado/CSV#2]
RFC4180 is quite clear that raw CR and LF can occur individually or together within a quoted field:

    escaped = DQUOTE *(TEXTDATA / COMMA / CR / LF / 2DQUOTE) DQUOTE

I believe the intention is that they be treated literally.  However:

```
$ echo $'"a\r\r\rb"' | extended
["ab"]

$ echo $'"a\r\r\rb"' | compliant
["ab"]

$ xxd 2.csv
00000000: 2261 0d0a 0d62 220a                      "a...b".  # i.e. " a CR LF CR b " LF

$ extended  < 2.csv
["a\nb"]

$ compliant  < 2.csv
["a\nb"]

```

It would probably be best if the "extended" mode also treated CR and LF characters within quoted fields literally, at least by default.

**Comment by fadado** [comment]
> It would probably be best if the "extended" mode also treated CR and LF characters within quoted fields literally

Done!

```
$$ echo  -e ',"a\r\r\rb"' | ./compliant 
[null,"a\r\r\rb"]
```

Edited and fixed: I just remembered controls must be escaped!
